version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - common-network
    volumes:
      - redis-data:/data

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "9000:9000"
    networks:
      - common-network
    environment:
    - CLICKHOUSE_USER=default
    - CLICKHOUSE_PASSWORD=
    - CLICKHOUSE_DB=default
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  analytics-service:
    build:
      context: .
    container_name: analytics-service
    ports:
      - "${GRPC_PORT}:50051"
      - "${GW_PORT}:8080"
    networks:
      - common-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
    depends_on:
      - redis
      - clickhouse
    command: ["dockerize", "-wait", "tcp://clickhouse-server:9000", "-timeout", "30s", "./main"]

networks:
  common-network:
    driver: bridge

volumes:
  redis-data:
  clickhouse-data: