version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - common-network
    volumes:
      - redis-data:/data

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "${CLICKHOUSE_PORT}:9000"
    networks:
      - common-network
    environment:
    - CLICKHOUSE_USER=default
    - CLICKHOUSE_PASSWORD=
    - CLICKHOUSE_DB=default
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host=localhost", "--query=SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate
    container_name: migrate
    networks:
      - common-network
    depends_on:
      clickhouse:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "/bin/sh", "-c", "migrate -path=/migrations -database 'clickhouse://default:@clickhouse:9000/default' up" ]

  analytics-service:
    build:
      context: .
    container_name: analytics-service
    ports:
      - "${GRPC_PORT}:50051"
      - "${GW_PORT}:8080"
    networks:
      - common-network
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
    depends_on:
      - redis
      - clickhouse
    command: ["dockerize", "-wait", "tcp://clickhouse-server:9000", "-timeout", "30s", "./main"]

networks:
  common-network:
    driver: bridge

volumes:
  redis-data:
  clickhouse-data:
  