// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: proto/stats/stats.proto

package stats

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // начало периода, ISO8601
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`     // конец периода, ISO8601
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetStatsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueUsers int32 `protobuf:"varint,1,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"` // количество уникальных пользователей
	TotalEvents int32 `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"` // общее количество событий
	// Список самых посещаемых URL
	MostVisitedUrls []*MostVisitedUrl `protobuf:"bytes,3,rep,name=most_visited_urls,json=mostVisitedUrls,proto3" json:"most_visited_urls,omitempty"`
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetUniqueUsers() int32 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

func (x *GetStatsResponse) GetTotalEvents() int32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *GetStatsResponse) GetMostVisitedUrls() []*MostVisitedUrl {
	if x != nil {
		return x.MostVisitedUrls
	}
	return nil
}

type MostVisitedUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`      // URL-адрес
	Count int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // количество посещений
}

func (x *MostVisitedUrl) Reset() {
	*x = MostVisitedUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stats_stats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MostVisitedUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostVisitedUrl) ProtoMessage() {}

func (x *MostVisitedUrl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostVisitedUrl.ProtoReflect.Descriptor instead.
func (*MostVisitedUrl) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{2}
}

func (x *MostVisitedUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MostVisitedUrl) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_stats_stats_proto protoreflect.FileDescriptor

var file_proto_stats_stats_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x41, 0x0a, 0x11, 0x6d, 0x6f, 0x73, 0x74, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64,
	0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x2e, 0x4d, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x55,
	0x72, 0x6c, 0x52, 0x0f, 0x6d, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x55,
	0x72, 0x6c, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x4d, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x73, 0x69, 0x74,
	0x65, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x65, 0x0a,
	0x0c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x12, 0x3a, 0x01, 0x2a, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_stats_stats_proto_rawDescOnce sync.Once
	file_proto_stats_stats_proto_rawDescData = file_proto_stats_stats_proto_rawDesc
)

func file_proto_stats_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_stats_stats_proto_rawDescData)
	})
	return file_proto_stats_stats_proto_rawDescData
}

var file_proto_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_stats_stats_proto_goTypes = []any{
	(*GetStatsRequest)(nil),  // 0: stats.GetStatsRequest
	(*GetStatsResponse)(nil), // 1: stats.GetStatsResponse
	(*MostVisitedUrl)(nil),   // 2: stats.MostVisitedUrl
}
var file_proto_stats_stats_proto_depIdxs = []int32{
	2, // 0: stats.GetStatsResponse.most_visited_urls:type_name -> stats.MostVisitedUrl
	0, // 1: stats.StatsService.GetStats:input_type -> stats.GetStatsRequest
	1, // 2: stats.StatsService.GetStats:output_type -> stats.GetStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stats_stats_proto_init() }
func file_proto_stats_stats_proto_init() {
	if File_proto_stats_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_stats_stats_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stats_stats_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stats_stats_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MostVisitedUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_stats_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_stats_proto = out.File
	file_proto_stats_stats_proto_rawDesc = nil
	file_proto_stats_stats_proto_goTypes = nil
	file_proto_stats_stats_proto_depIdxs = nil
}
